"use client";
import { Alarm, ArrowSquareOut, ChatCircleDots, Clock, MapPin, UsersThree, VideoCamera } from "@phosphor-icons/react";
import { useI18n } from "@/lib/i18n";

export type AgendaItem={id:string;kind:string;source:string;title:string;start:unknown;end:unknown;status:string;description?:string;priority?:string;channel?:string;attendees?:string[];location?:string;join_url?:string;edit_url?:string;reminder_minutes?:number};
export function instant(value:unknown):string|null {if(typeof value==="string")return value;if(value&&typeof value==="object"){const row=value as {dateTime?:string;date?:string;timeZone?:string};if(row.dateTime&&row.timeZone==="UTC"&&!/[zZ]|[+-]\d\d:\d\d$/.test(row.dateTime))return `${row.dateTime}Z`;return row.dateTime??row.date??null;}return null;}
const safeUrl=(value?:string)=>value?.startsWith("https://")?value:undefined;
export function Agenda({items,timezone}:{items:AgendaItem[];timezone:string}){
  const {locale,t}=useI18n();const format=(value:unknown,withDate=false)=>{const raw=instant(value);return raw?new Intl.DateTimeFormat(locale,{...(withDate?{weekday:"short",day:"numeric",month:"short"}:{}),hour:"2-digit",minute:"2-digit",timeZone:timezone}).format(new Date(raw)):t("Без времени","No time")};
  const kind=(value:string)=>({event:t("Событие","Event"),task:t("Задача","Task"),timer:t("Таймер","Timer"),reminder:t("Напоминание","Reminder")}[value]??value);
  const ordered=[...items].sort((a,b)=>(Date.parse(instant(a.start)??"")||Number.MAX_SAFE_INTEGER)-(Date.parse(instant(b.start)??"")||Number.MAX_SAFE_INTEGER));
  return <div className="agenda">{ordered.map(item=>{const join=safeUrl(item.join_url);const edit=safeUrl(item.edit_url);const prompt=encodeURIComponent(`${t("Измени событие","Change event")} «${item.title}» ${format(item.start,true)}. `);return <article className="agendaItem" key={`${item.source}-${item.id}`}><div className="agendaTime"><Clock size={18}/><span>{format(item.start)}</span>{instant(item.end)&&<span className="muted">{t("до","to")} {format(item.end)}</span>}</div><div className="agendaBody"><div className="agendaTitle"><strong>{item.title}</strong><span className="status">{kind(item.kind)} · {item.source}</span></div>{item.description&&<p>{item.description}</p>}<div className="agendaMeta">{item.kind==="timer"&&<span><Clock size={16}/>{t("Запущен","Started")}: {format(item.start,true)}. {t("Сработает","Ends")}: {format(item.end,true)}</span>}{typeof item.reminder_minutes==="number"&&<span><Alarm size={16}/>{t("Напоминание за","Reminder")} {item.reminder_minutes} {t("минут","minutes")}</span>}{item.attendees?.length?<span><UsersThree size={16}/>{item.attendees.join(", ")}</span>:null}{item.location&&!join?<span><MapPin size={16}/>{item.location}</span>:null}</div><div className="agendaActions">{join&&<a className="button" href={join} target="_blank" rel="noreferrer"><VideoCamera size={18}/>{t("Войти во встречу","Join meeting")}</a>}{edit&&<a className="button secondary" href={edit} target="_blank" rel="noreferrer"><ArrowSquareOut size={18}/>{t("Открыть в календаре","Open in calendar")}</a>}{item.kind==="event"&&<a className="button secondary" href={`/?draft=${prompt}`}><ChatCircleDots size={18}/>{t("Изменить через чат","Change in chat")}</a>}</div></div></article>})}</div>;
}
